### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by joshuamb419**
Provide wylx with a readme

### CODE REVIEW

**Review by VVill-ga — APPROVED** [review]
A good start for documentation.

**Review by VVill-ga — APPROVED** [review]
A good start for documentation.

**Review by 1Revenger1 — CHANGES_REQUESTED** [review]
Wanna add build instructions real quick?
I'm pretty sure it is as simple as `./gradlew build` and `./build/install/WylxBot/bin/WylxBot` to run the result.

Edit: Oh and minimum JDK version too. Believe we use 17.

**Comment by joshuamb419** [comment]
Should only need to do `./gradlew build` and then `./gradlew run` or just `./gradlew build run`

**Review by 1Revenger1 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
